namespace: razubuddy
name: microservice
version: 0.0.1
readme: README.md
authors: []
description: ""
repository: https://github.com/razubuddy/ansible-collections/microservice
build_ignore:
  - '*.tar.gz'
