---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Execute restart sshd
  systemd:
    name: ssh
    state: restarted
  listen: "restart sshd"
  async: 5
  poll: 0

- name: Wait for sshd to start
  wait_for_connection:
    delay: 5
    timeout: 60
  listen: "restart sshd"
