---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx package to install.
nginx_package_name: "nginx"

nginx_service_state: started
nginx_service_enabled: true

nginx_worker_processes: >-
  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "75"
nginx_keepalive_requests: "600"

nginx_server_tokens: "on"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

# Listen on IPv6 (default: true)
nginx_listen_ipv6: true

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

# name of the vhost
nginx_app_name: app

nginx_user_dir: /var/www
nginx_user_key: change_me
nginx_site_dir: site

# domain
#nginx_server_name: example.com

nginx_certificate_email: change.me@email.com

# certbot | provided | selfsigned
nginx_ssl_mode: certbot

nginx_upstream_files:
  - file: "{{ nginx_app_name }}_upstreams_blue"
    upstreams:
      - name: "{{ nginx_app_name }}-api"
        server: localhost:8081
      - name: "{{ nginx_app_name }}-api-staging"
        server: localhost:8082
  - file: "{{ nginx_app_name }}_upstreams_green"
    upstreams:
      - name: "{{ nginx_app_name }}-api"
        server: localhost:8082
      - name: "{{ nginx_app_name }}-api-staging"
        server: localhost:8081

nginx_internal_vhosts: [ ]
#nginx_internal_vhosts:
#  - port: 8080
#    locations:
#      - path: "/api"
#        proxy_pass: "http://{{ nginx_app_name }}-api/api"
#        handle_cors: false


nginx_vhost_locations:
  - path: "/api"
    proxy_pass: "http://{{ nginx_app_name }}-api/api"
    handle_cors: true
  - path: "/api-staging"
    proxy_pass: "http://{{ nginx_app_name }}-api-staging/api"
    handle_cors: false

nginx_vhost_extra_locations: [ ]

nginx_vhost_ssl_privkey_path: "/etc/ssl/{{ nginx_app_name }}_privkey.pem"
nginx_vhost_ssl_privkey_size: 4096
nginx_vhost_ssl_privkey_type: RSA
nginx_vhost_ssl_csr_path: "/etc/ssl/{{ nginx_app_name }}.csr"
nginx_vhost_ssl_cert_path: "/etc/ssl/{{ nginx_app_name }}_cert.pem"
nginx_vhost_ssl_dhparam_path: /etc/ssl/dhparam.pem
nginx_vhost_ssl_dhparam_size: 2048
